=== asabeeh18/PROgrammin/Java/NetBeans/Training/src/y.dtd
<!ELEMENT youtube (channel+ , user+ )>
<!ELEMENT  channel  (cid,cname,category)*>
<!ELEMENT  user  (uid,uname,dob,country,password)*>
<!ELEMENT  cid (#PCDATA)>
<!ELEMENT  cname (#PCDATA)>
<!ELEMENT  category (#PCDATA)>
<!ELEMENT  uid (#PCDATA)>
<!ELEMENT  uname (#PCDATA)>
<!ELEMENT  dob (#PCDATA)>
<!ELEMENT  country (#PCDATA)>
<!ELEMENT  password (#PCDATA)>

=== asabeeh18/PROgrammin/Java/NetBeans/Training/src/as.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE youtube SYSTEM "y.dtd">
<youtube>
<channel>

		<cid>1</cid>

		<cname>shuntz</cname>

		<category>educational</category>

	</channel>
<channel>
		<cid>2</cid>
		<cname>sony</cname>
		<category>music</category>
	</channel>
<user>
		<uid>2</uid>
		<uname>Chiranjiv Ganatra</uname>
		<dob>16-4-1995</dob>
		<country>India</country>
		<password>vit123</password>
	</user>

	<user>

		<uid>1</uid>

		<uname>Aditya Awalkar</uname>

		<dob>10-2-1995</dob>

		<country>India</country>

		<password>vit123</password>

	</user>
</youtube>
